### ISSUE TITLE
Spaces in the Plugins-Folder Name are not supported

### ISSUE THREAD

**Issue by hoffi** [matryer/bitbar#130]
Spaces are not escaped. When i do "Run in terminal..." i get this error: 
```sh
~/BitBar Plugins/test.5s.sh
zsh: no such file or directory: ~/BitBar
```

**Comment by matryer** [comment]
I believe this is solved in https://github.com/matryer/bitbar/pull/50 - can you try with the 1.4beta release?

**Comment by hoffi** [comment]
I have tried it with 1.4 beta

**Comment by tresni** [comment]
tresni@a847f43 was the simplest fix I could come up with.  I actually looked into escaping strings ala DTerm's [DTShellUtilities methods](https://github.com/bdrister/dterm/blob/master/Utilities/DTShellUtilities.m), but it just seemed overkill. `performMenuItemOpenTerminalAction` may still have issues if the `bash` param has spaces.  But honestly the AppleScript -> Terminal bridge is going to have weirdness, I'm not sure there's a great way around that.

**Comment by matryer** [comment]
Closing since #193 is closed.

**Comment by tresni** [comment]
@matryer #193 was closed as a duplicate of this, and then this was closed because #193 was closed?  Sounds circular :)
